config/routes.rb
Rails.application.routes.draw do
  resources :messages do
	  collection do
	    get 'showlast'
	  end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message
  include Mongoid::Document
  field :title, type: String
  field :body, type: String
  field :multimedia, type: String
  field :links, type: String
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  def showlast
  end

  # GET /messages/new
  def new
    @message = Message.new
  end


  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: 'Message was successfully created.' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
    
    Rails.cache.fetch('lastmessage', force: true, expires_in: 30.minutes) do
        @message
    end

    puts 'sdfsdfds'
    puts Rails.cache.instance_variable_get(:@data).keys.map{|key| {key: key, value: Rails.cache.fetch(key)}}


    puts 'sdfsdfds'
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:title, :body, :multimedia, :links)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bdnr</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_form.html.erb
<%= form_with(model: message, local: true) do |form| %>
  <% if message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_field :body %>
  </div>

  <div class="field">
    <%= form.label :multimedia %>
    <%= form.text_field :multimedia %>
  </div>

  <div class="field">
    <%= form.label :links %>
    <%= form.text_field :links %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<div class="jumbotron text-center">
<h1>FIREBASE</h1>
<p> App: NotificacionesYa </p>
</div>

<div class="container">
<table class="table table-striped">
  <h3> Mensajes disponibles para Enviar a Usuarios: </h3>
  <div class="container">
  <%= link_to 'Crear nuevo mensaje', new_message_path, :class => "btn btn-primary"  %>
  <%= link_to 'Ver mensaje en Cache', '/messages/showlast', :class => "btn btn-primary"  %>
  </div>

  <thead>
    <tr>
      <th>Título</th>
      <th>Cuerpo</th>
      <th>Multimedia</th>
      <th>Links</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.title  %></td>
        <td><%= message.body %></td>
        <td><%= message.multimedia %></td>
        <td><%= message.links %></td>
          <td><%= link_to 'Mostrar', message, :class => "btn btn-primary" %></td>
          <td><%= link_to 'Eliminar', message, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-primary" %></td>
          <td><%= link_to 'Enviar a todos los Usuarios de la App', '#', :class => "btn btn-primary" %></td>
          <td><%= link_to 'Enviar a solo a Usuarios Móvil', '#', :class => "btn btn-primary" %></td>
          <td><%= link_to 'Enviar a solo a Usuarios Web', '#', :class => "btn btn-primary" %></td>
          <td><%= link_to 'Enviar a solo a Usuarios SMS', '#', :class => "btn btn-primary" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>


<br>

app/views/messages/new.html.erb
<div class='container'>

<h1>New Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Back', messages_path, :class => "btn btn-primary" %>
</div>

app/views/messages/show.html.erb
<div class='container'>
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @message.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @message.body %>
</p>

<p>
  <strong>Multimedia:</strong>
  <%= @message.multimedia %>
</p>

<p>
  <strong>Links:</strong>
  <%= @message.links %>
</p>

<%= link_to 'Edit', edit_message_path(@message), :class => "btn btn-primary"  %> |
<%= link_to 'Back', messages_path, :class => "btn btn-primary"  %>
</div>

app/views/messages/showlast.html.erb
<div class='container'>
  <h2> Último mensaje creado (obtenido del Caché) </h2>

<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= 
  	Rails.cache.read('lastmessage').title
  %>
</p>

<p>
  <strong>Body:</strong>
<%= 
  	Rails.cache.read('lastmessage').body
  %></p>

<p>
  <strong>Multimedia:</strong>
<%= 
  	Rails.cache.read('lastmessage').multimedia
  %></p>

<p>
  <strong>Links:</strong>
	<%= 
  	Rails.cache.read('lastmessage').links
  	%>
</p>

<%= link_to 'Back', '/messages', :class => "btn btn-primary"  %>
</div>